### ISSUE TITLE
Add support for formatted text

### ISSUE THREAD

**Issue by Coder2195** [codyebberson/wglt#28]
Add bold, italic, and underlined support.

**Comment by codyebberson** [comment]
Hi, thanks for your interest in wglt.

Unfortunately, formatted text does not align my goals for this project.  I added a short section to the readme about project limitations and my intentions: https://github.com/codyebberson/wglt/commit/a9f2288101549cd491b423688e97d3dbbb831d7c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R67-R81

For some use cases, you could achieve bold, italic, and underline by prerendering the glyphs in a custom font.  
* Demo: https://wglt.js.org/examples/font.html
* Source: https://github.com/codyebberson/wglt/blob/main/examples/font.ts

Sorry to disappoint.  Thanks again for your interest.
