### ISSUE TITLE
Display Functions not present on Terminal Class

### ISSUE THREAD

**Issue by HexSleeves** [codyebberson/wglt#29]
I don't know if I setup my typescript incorrectly, but it says the Terminal class doesn't actually have the draw functions.

<img width="630" alt="CleanShot 2022-06-30 at 19 39 45@2x" src="https://user-images.githubusercontent.com/9278174/176800462-320f3598-1b0c-418d-b423-ff6c22dfc426.png">

Looking at the source it extends `Console` so they should be there...

**Comment by HexSleeves** [comment]
Did some more digging. Seems like the output .d.ts file is borked. There are a couple options. 

Either run `tsc` but dont specify an outfile which will create declaration files for each typescript file that exist (larger bundle size).

Use rollup-dts  to compile the types into a single declaration file

**Comment by codyebberson** [comment]
Fixed in https://github.com/codyebberson/wglt/pull/31
